# Generated by Django 5.0 on 2025-10-15 08:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificador de la puerta', max_length=100, unique=True, verbose_name='Nombre')),
                ('ubicacion', models.CharField(help_text='Ubicación física de la puerta', max_length=200, verbose_name='Ubicación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='CERRADA', max_length=10, verbose_name='Estado Actual')),
                ('activa', models.BooleanField(default=True, help_text='La puerta está operativa', verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Puerta',
                'verbose_name_plural': 'Puertas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LockState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, help_text='Si está activo, solo usuarios autorizados pueden acceder', verbose_name='Seguro Activo')),
                ('fecha_cambio', models.DateTimeField(auto_now=True, verbose_name='Fecha de Último Cambio')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('puerta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguro', to='access_control.door', verbose_name='Puerta')),
                ('usuario_cambio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_seguro', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Realizó el Cambio')),
            ],
            options={
                'verbose_name': 'Estado del Seguro',
                'verbose_name_plural': 'Estados de Seguros',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('DIRECTOR', 'Director'), ('MAESTRO', 'Maestro'), ('ALUMNO', 'Alumno')], default='ALUMNO', max_length=10, verbose_name='Rol')),
                ('codigo_acceso', models.CharField(help_text='Código numérico para acceso físico', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El código de acceso solo puede contener números', regex='^[0-9]+$')], verbose_name='Código de Acceso')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Número de teléfono debe tener entre 9 y 15 dígitos', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, help_text='Usuario puede acceder al sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['user__username'],
            },
        ),
    ]
